# Creating a New Subset: North Carolina County Premature Deaths

## Overview

This notebook will explain the steps to create a subset containing each North Carolina county's premature death count and average poor mental health days for the year 2015 in Google CoLab.


The overall process for creating the desired subset is:

1. **Create** and **mount** a Google Drive folder containing the .csv file
2. Import necessary **packages**
3. Use the .csv file to create a **dataframe**
4. **Filter** data to create a **subset** with the necessary information
5. **Export** the subset as a new .csv file

## Getting Started

1. Begin by creating a **Google Drive folder** to upload the .csv file into.
    - Recommendation: Name the folder something you would easily remember.
2. **Mount** Google Drive as seen below.
    - Make sure to allow full access to your Drive, or it will not work.

In [ ]:
from google.colab  import drive
drive.mount('/content/drive')

Mounted at /content/drive

### Packages

1. **Import** numpy and pandas as seen below.
  - Recommendation: Nickname numpy and pandas as something you will remember by adding "as [insert nickname]".

In [ ]:
import numpy as np
import pandas as pd

### Creating a Dataframe

1. Create a name for your dataframe.
  - Below it is named "dat".
  - For every instance "dat" is used, make sure to use the name you gave your dataframe.
2. Use **=pd.read_csv(location of file)** to turn your .csv into a data frame.
  - Make sure to list every folder your .csv if part of. It will look something like below, but the folders will likely not be named the same.

In [ ]:
dat=pd.read_csv('drive/My Drive/English 105/CountyHealthData_2014-2015.csv')

## Creating the Subset

After importing the data, the desired columns and rows within the .csv will be separated from the rest. First, a .value_counts() function is used to show how many North Carolina rows there are to work with. Then, .loc and .iloc functions will be used to separate the necessary columns and rows.

### Collecting Values

1. Use the **.value_counts()** function, as seen below, to gather how many times each State is represented in the data.
  - NC (North Carolina) appears 200 times, so there will be 200 rows of NC data.

In [ ]:
dat.State.value_counts()

State
TX    469
GA    318
VA    266
KY    240
MO    229
IL    204
NC    200
KS    199
IA    198
TN    190
IN    184
OH    176
MN    174
MI    164
MS    163
NE    157
OK    154
AR    150
WI    144
PA    134
FL    134
AL    134
LA    128
NY    124
CO    119
SD    117
CA    114
WV    110
MT     92
ND     92
SC     92
ID     84
WA     78
OR     67
NM     64
UT     54
MD     48
WY     46
AK     46
NJ     42
ME     32
NV     32
AZ     30
VT     28
MA     28
NH     20
CT     16
RI     10
HI      8
DE      6
DC      1
Name: count, dtype: int64

Using an **inner** and **outer** function will create a table showing only NC values.

2. The **inner function**, dat["State"] == "NC" will find all "NC" rows.

3. The **outer function**, dat[...] selects the rows inside the brackets.

4. **Combine** the two functions to isolate the NC rows, as seen below.

In [ ]:
dat[dat["State"] == "NC"]

,State,Region,Division,County,FIPS,GEOID,SMS Region,Year,Premature death,Poor or fair health,...,Drug poisoning deaths,Uninsured adults,Uninsured children,Health care costs,Could not see doctor due to cost,Other primary care providers,Median household income,Children eligible for free lunch,Homicide rate,Inadequate social support
3243,NC,South,South Atlantic,Alamance County,37001,37001,Region 20,1/1/2014,7123.0,0.192,...,10.48,0.259,0.073,8640.0,0.167,46.0,41394,0.444,4.94,0.202
3244,NC,South,South Atlantic,Alamance County,37001,37001,Region 20,1/1/2015,7291.0,0.192,...,12.38,0.249,0.088,9050.0,0.167,56.0,43001,0.455,4.60,NaN
3245,NC,South,South Atlantic,Alexander County,37003,37003,Region 20,1/1/2014,7974.0,0.178,...,22.74,0.240,0.077,9316.0,0.205,30.0,39655,0.417,6.27,0.273
3246,NC,South,South Atlantic,Alexander County,37003,37003,Region 20,1/1/2015,8079.0,0.178,...,24.04,0.239,0.076,9242.0,0.205,32.0,46064,0.449,7.20,NaN
3247,NC,South,South Atlantic,Alleghany County,37005,37005,Insuff Data,1/1/2014,8817.0,0.234,...,18.18,0.320,0.131,9585.0,0.210,55.0,34046,0.523,NaN,0.215
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3438,NC,South,South Atlantic,Wilson County,37195,37195,Region 20,1/1/2015,8028.0,0.159,...,7.31,0.262,0.079,9450.0,0.107,77.0,40772,0.556,9.60,NaN
3439,NC,South,South Atlantic,Yadkin County,37197,37197,Region 20,1/1/2014,7893.0,0.207,...,18.45,0.252,0.097,10084.0,0.158,32.0,40012,0.422,3.76,0.241
3440,NC,South,South Atlantic,Yadkin County,37197,37197,Region 20,1/1/2015,7258.0,0.207,...,20.21,0.242,0.094,10998.0,0.158,32.0,40998,0.455,NaN,NaN
3441,NC,South,South Atlantic,Yancey County,37199,37199,Region 15,1/1/2014,6872.0,0.193,...,20.79,0.268,0.110,7707.0,0.158,79.0,36019,0.477,NaN,0.176
3442,NC,South,South Atlantic,Yancey County,37199,37199,Region 15,1/1/2015,8917.0,0.193,...,28.02,0.246,0.091,7870.0,0.158,74.0,35866,0.469,NaN,NaN

5. **Rename** the previous line of code to NC using **NC =**, as seen below, to make the next steps easier.

In [ ]:
NC = dat[dat["State"] == "NC"]

### Locating Values

Use **.loc** and **.iloc** functions to isolate desired values. This is especially useful for when desired values are in nonconsecutive columns.

1. Using your renamed function, use **.loc** to isolate the desired columns.
2. Use a **colon ":"** to select *every* row.
3. After the colon **list the desired columns** separated by commas.
  - The desired columns are: **County, Year, Premature death, and Poor mental health days**.
4. As seen at the bottom of the table, 200 rows are created, two for each NC County, and the four desired columns.

In [ ]:
NC.loc[:,["County","Year","Premature death", "Poor mental health days"]]

                County      Year  Premature death  Poor mental health days
3243   Alamance County  1/1/2014           7123.0                      3.6
3244   Alamance County  1/1/2015           7291.0                      3.6
3245  Alexander County  1/1/2014           7974.0                      4.6
3246  Alexander County  1/1/2015           8079.0                      4.6
3247  Alleghany County  1/1/2014           8817.0                      4.4
...                ...       ...              ...                      ...
3438     Wilson County  1/1/2015           8028.0                      3.1
3439     Yadkin County  1/1/2014           7893.0                      4.6
3440     Yadkin County  1/1/2015           7258.0                      4.6
3441     Yancey County  1/1/2014           6872.0                      4.1
3442     Yancey County  1/1/2015           8917.0                      4.1

[200 rows x 4 columns]

5. **Rename** the previous line of code to CD2015 using **CD2015 =**

In [ ]:
CD2015 = NC.loc[:,["County","Year","Premature death", "Poor mental health days"]]

Using your renamed function, use the **.iloc** function to isolate only the rows for the year 2015. Here, every 2015 row is an **even-numbered row**.
  
6.  Use **.iloc** to isolate desired rows.
7. Inside the brackets, use **1::2** to select every other row.
  - The "1" indicates to start one row down.

In [ ]:
CD2015.iloc[1::2]

                County      Year  Premature death  Poor mental health days
3244   Alamance County  1/1/2015           7291.0                      3.6
3246  Alexander County  1/1/2015           8079.0                      4.6
3248  Alleghany County  1/1/2015           7324.0                      4.4
3250      Anson County  1/1/2015           9599.0                      NaN
3252       Ashe County  1/1/2015           7900.0                      3.5
...                ...       ...              ...                      ...
3434      Wayne County  1/1/2015           8763.0                      3.5
3436     Wilkes County  1/1/2015           8673.0                      4.4
3438     Wilson County  1/1/2015           8028.0                      3.1
3440     Yadkin County  1/1/2015           7258.0                      4.6
3442     Yancey County  1/1/2015           8917.0                      4.1

[100 rows x 4 columns]

8. You have now successfully created a new subset!

## Exporting the New Subset

1. **Rename** the previous line of code to CD2015_subset using **CD2015_subset =**

In [ ]:
CD2015_subset =  CD2015.iloc[1::2]

2. **Convert** your subset to a .csv by using **.to_csv**.
3. Include what you want your new .csv file to be **named** in the brackets.
  - Recommendation: Include **index=False** after the name to exclude the row numbers from your .csv.

In [ ]:
CD2015_subset.to_csv("CD2015_subset.csv", index=False)

Run this function and your new .csv will appear under the folder icon on the sidebar. From here you can download your new subset.

Happy coding!